spring:
  redis:
    nodes: >
      172.20.154.75:7011,
      172.20.154.75:7013,
      172.20.154.75:7015
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 100
#        min-idle: 2
#    port: 7011
#    host: 172.20.154.75
    timeout:
      connection: 300
      command: 3000

